name: Build ISO

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the code
      uses: actions/checkout@v3

    # Step 2: Install necessary dependencies
    # - xorriso: A tool for creating ISO 9660 filesystems
    # - grub-pc-bin: Contains GRUB binaries needed for bootable ISOs
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorriso grub-pc-bin

    # Step 3: Compile the OS code
    # In this example, the OS code is already written in Python,
    # so this step is more about organizing the files.
    - name: Compile the OS code
      run: |
        mkdir -p iso/boot/grub
        cp -r boot/ kernel/ bin/ lib/ etc/ home/ iso/
        
        # Create a basic GRUB configuration file
        cat << EOF > iso/boot/grub/grub.cfg
        menuentry "My Portable OS" {
            insmod linux
            linux /kernel/kernel.py
        }
        EOF

    # Step 4: Create an ISO file
    - name: Create ISO
      run: |
        xorriso -as mkisofs \
        -R -J -c boot/grub/stage2_eltorito \
        -b boot/grub/i386-pc/eltorito.img \
        -no-emul-boot -boot-load-size 4 -boot-info-table \
        -o my_portable_os.iso iso/

    # Step 5: Upload the ISO file as an artifact
    - name: Upload ISO file
      uses: actions/upload-artifact@v3
      with:
        name: my_portable_os_iso
        path: my_portable_os.iso
