name: Compile System Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install -y gcc xorriso

    - name: Compile system.c
      run: gcc system.c -o system

    - name: Create ISO directory structure
      run: |
        mkdir -p iso/boot/grub
        cp system iso/boot/
        echo 'set timeout=0' > iso/boot/grub/grub.cfg
        echo 'set default=0' >> iso/boot/grub/grub.cfg
        echo 'menuentry "My OS" {' >> iso/boot/grub/grub.cfg
        echo '  multiboot /boot/system' >> iso/boot/grub/grub.cfg
        echo '  boot' >> iso/boot/grub/grub.cfg
        echo '}' >> iso/boot/grub/grub.cfg

    - name: Create ISO file
      run: xorriso -as mkisofs -R -b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table -o my_os.iso iso

    - name: Upload ISO file
      uses: actions/upload-artifact@v2
      with:
        name: my_os
        path: my_os.iso
