name: Build Windows Executable # Nombre del flujo de trabajo

on: # Eventos que desencadenan el flujo de trabajo
  push:
    branches: [ main ] # Se ejecuta cuando se hace push a la rama main
  pull_request:
    branches: [ main ] # Se ejecuta cuando se abre un pull request a la rama main

jobs: # Tareas a ejecutar

  build: # Nombre de la tarea
    runs-on: windows-latest # Ejecuta la tarea en un runner de Windows
    
    steps: # Pasos a seguir
    - uses: actions/checkout@v4 # Obtiene el código fuente
    
    - name: Set up Python # Configura Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # Usa la versión 3.9 de Python
    
    - name: Install dependencies # Instala dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build executable # Construye el ejecutable
      run: |
        pyinstaller --onefile sys.spec
    
    - name: Upload artifact # Sube el ejecutable como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/sys.exe
